# Generated by Django 6.0.3 on 2026-03-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capital', models.CharField(max_length=100)),
                ('square', models.DecimalField(decimal_places=2, max_digits=10)),
                ('population', models.IntegerField()),
                ('flag', models.URLField()),
            ],
        ),
    ]
