# Generated by Django 6.0.3 on 2026-04-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country_learner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='flag',
        ),
        migrations.AlterField(
            model_name='country',
            name='square',
            field=models.IntegerField(),
        ),
    ]
