# Generated by Django 6.0.3 on 2026-04-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country_learner', '0003_usercountry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='population',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='country',
            name='square',
            field=models.CharField(max_length=100),
        ),
    ]
