# Generated by Django 6.0.3 on 2026-04-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country_learner', '0004_alter_country_population_alter_country_square'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='world_part',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='population',
            field=models.CharField(max_length=100),
        ),
    ]
