# Generated by Django 6.0.3 on 2026-04-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country_learner', '0005_country_world_part_alter_country_population'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='world_part',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
